### ISSUE TITLE
Exception: Must have called .setTargets() before calling create()

### ISSUE THREAD

**Issue by jdreesen** [cedricziel/idea-php-typo3-plugin#109]
Windows: 7 (64bit)
PhpStorm: 2017.3
Extension: v0.2.27

I just got the following Exception:

```
Must have called .setTargets() before calling create()
java.lang.AssertionError: Must have called .setTargets() before calling create()
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.a(NavigationGutterIconBuilder.java:229)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.createGutterIconRenderer(NavigationGutterIconBuilder.java:250)
	at com.intellij.codeInsight.navigation.NavigationGutterIconBuilder.createLineMarkerInfo(NavigationGutterIconBuilder.java:194)
	at com.cedricziel.idea.typo3.codeInsight.RouteLineMarkerProvider.lambda$collectNavigationMarkers$0(RouteLineMarkerProvider.java:42)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.cedricziel.idea.typo3.codeInsight.RouteLineMarkerProvider.collectNavigationMarkers(RouteLineMarkerProvider.java:38)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:213)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:112)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:107)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by cedricziel** [comment]
A new release has been tagged. Thx for the report. (There's a build artifact on the PR if you want to have it right now)

**Comment by jdreesen** [comment]
Thx for the quick fix :)

I think I'm going to wait for the approval from JetBrains and update it the default way.

**Comment by cedricziel** [comment]
Your choice :)

Hint: the `releases` page contains the "official" jars that are built on a git tag through travis, if you want those - these are equal byte for byte with the releases thorugh the plugin repository (plus I sign the tags so these are really genuine).
