### ISSUE TITLE
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by artspb** [cedricziel/idea-php-typo3-plugin#167]
We've got the exception from one of our users. Please keep in mind that indices are not available in the dumb mode. `com.intellij.openapi.project.DumbService` is here for your convenience.

<details>
  <summary>Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation</summary>
<pre><code>com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:77)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:761)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:710)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:693)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:334)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:310)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:681)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:661)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:715)
	at com.cedricziel.idea.typo3.container.IconProvider.collectIcons(IconProvider.java:76)
	at com.cedricziel.idea.typo3.container.IconProvider.collect(IconProvider.java:46)
	at com.cedricziel.idea.typo3.container.IconProvider.getInstance(IconProvider.java:30)
	at com.cedricziel.idea.typo3.TYPO3CMSProjectComponent.lambda$null$0(TYPO3CMSProjectComponent.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921)
	at com.cedricziel.idea.typo3.TYPO3CMSProjectComponent.lambda$projectOpened$1(TYPO3CMSProjectComponent.java:37)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)</code></pre></details>

**Comment by andreasfernandez** [comment]
I run into this issue since updating PhpStorm to 2021.1, using version 0.2.4 of the plugin.

**Comment by cedricziel** [comment]
Version 0.2.4 is a very old plugin version. Your IDE downgraded the plugin.

I have adjusted the compatibility range, so please disable the plugin and wait for an update :)
