### ISSUE TITLE
Project indexing loop

### ISSUE THREAD

**Issue by w010** [cedricziel/idea-php-typo3-plugin#327]
I've noticed lately PHPStorm has problems with indexing projects (I think it happens since 2020 update). One problem is when I have two projects open in same time, it stucks on indexing in both of them. When I close one, it finishes.
Second and worse problem is with one of mine projects, which can't finish indexing at all. Looping on some subdir, and when I exclude this dir, it stucks on another random dir.
I suspected a bug in new Storm, but today I found out that your plugin is the reason - when disabled, everything starts to work fine, indexing always works as it used to earlier.
Your plugin is very helpful in my work, now I have to stop using it. So I hope you could possibly find a fix for this behaviour. 
I'm not really sure what info do you need to find a problem. This is what I found in logs:

`2020-07-01 12:13:41,295 [ 262734]   INFO - il.indexing.FileBasedIndexImpl - scheduleIndexRebuild, reason: checkRebuild 
2020-07-01 12:13:41,295 [ 262734]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 50ms; general responsiveness: ok; EDT responsiveness: ok 
2020-07-01 12:13:41,355 [ 262794]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 60ms; general responsiveness: ok; EDT responsiveness: ok 
2020-07-01 12:13:41,720 [ 263159]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 347ms; general responsiveness: ok; EDT responsiveness: ok 
2020-07-01 12:13:41,724 [ 263163]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 91 files to update 
2020-07-01 12:13:41,748 [ 263187]   INFO - l.indexing.impl.MapReduceIndex - An exception during updateWithMap(). Index com.cedricziel.idea.typo3.index.core_service_map will be rebuilt. 
com.intellij.util.indexing.StorageException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/util/io/EnumeratorStringDescriptor.save must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.updateWithMap(MapReduceIndex.java:367)
	at com.intellij.util.indexing.impl.MapReduceIndex.lambda$createIndexUpdateComputation$0(MapReduceIndex.java:247)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.runIndexUpdate(FileBasedIndexImpl.java:1325)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1256)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$20(FileBasedIndexImpl.java:1181)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:723)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1161)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1147)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$2(UnindexedFilesUpdater.java:130)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$1(CacheUpdateRunner.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$2(CacheUpdateRunner.java:224)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$createRunnable$3(CacheUpdateRunner.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:198)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by PSchwalkowski** [comment]
I'm facing the same problem. Indexing stuck in one place and not moving forward. After disabling your plugin everything is working fine again.

**Comment by MiroslawKmiec** [comment]
Same problem, stuck on indexing.  Removing your extension fix problem.

**Comment by hsz** [comment]
You should not leave the `object` variable unset:

https://github.com/cedricziel/idea-php-typo3-plugin/blob/master/typo3-cms/src/main/java/com/cedricziel/idea/typo3/index/externalizer/ObjectStreamDataExternalizer.java
