### ISSUE TITLE
IndexNotReadyException after update to 2021.1 EAP

### ISSUE THREAD

**Issue by vertexvaar** [cedricziel/idea-php-typo3-plugin#347]
Hi @cedricziel 

thank you for your honestly awesome plugin. After updating to the latest PhpStorm EAP i got following exception.

<details>
  <summary>Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation</summary>

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:697)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:649)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:495)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:301)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:92)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:80)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:554)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:965)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:940)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1015)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:1008)
	at com.cedricziel.idea.typo3.container.IconProvider.collectIcons(IconProvider.java:76)
	at com.cedricziel.idea.typo3.container.IconProvider.collect(IconProvider.java:46)
	at com.cedricziel.idea.typo3.container.IconProvider.getInstance(IconProvider.java:30)
	at com.cedricziel.idea.typo3.TYPO3CMSProjectComponent.lambda$null$0(TYPO3CMSProjectComponent.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:837)
	at com.cedricziel.idea.typo3.TYPO3CMSProjectComponent.lambda$projectOpened$1(TYPO3CMSProjectComponent.java:37)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

**Comment by liayn** [comment]
Confirmed. @cedricziel would be really nice if you could adjust this soonish. Thanks.

**Comment by cedricziel** [comment]
Please check your plugin versions - this plugin is not yet compatible with 2021.1 and your IDE did download an ancient version that did not have an upper boundary.

Related: https://github.com/cedricziel/idea-php-typo3-plugin/issues/348

**Comment by liayn** [comment]
@cedricziel  I run version 0.2.4. No update has been offered by phpstorm. (also not before the update to the EAP)

**Comment by cedricziel** [comment]
Your upgrade to 2021.1 effectively downgraded the extension to 0.2.4.

What I can eventually ask JetBrains is to mark the old versions incompatible so the downgrade wouldn't happen.

Would that help?

**Comment by cedricziel** [comment]
@liayn no, the version is "correct" in a sense. Starting january 2018, I started using the supported platform as version prefix - just as jetbrains do.

Please take a look at https://plugins.jetbrains.com/plugin/9496-typo3-cms-support/versions

203.6.1 is still the most recent version. It is plugin version 0.6.1 for the 203 IDEA platform.

**Comment by liayn** [comment]
Seems like the 0.2.4 version even works on 2021.1 except the mentioned error here. ;-)

**Comment by vertexvaar** [comment]
> this plugin is not yet compatible with 2021.1

As far as i am concerned we can close this issue since you opened #348 

> What I can eventually ask JetBrains is to mark the old versions incompatible so the downgrade wouldn't happen.
> Would that help?

This will prevent further issues of this kind :smile: 
I checked the Plugin version and it is, as you expected, 0.2.4.
I'd suggest to add a github issue template where issuers are asked to enter their phpstorm and plugin version.
