### ISSUE TITLE
PHPStorm 2121.1 - com.intellij.openapi.project.IndexNotReadyException

### ISSUE THREAD

**Issue by wbm-sbasler** [cedricziel/idea-php-typo3-plugin#353]
**Describe the bug**
After I updated my PHPStorm to the newest version 2121.1 i get an exception for this plugin

**To Reproduce**
1. Opten PHPStorm 2020.4 with TYPO3 plugin installed
2. Click on update and restart in the PHPStorm 2121.1 update dialog
3. After restart the exception occures
4. It occures after each start of PHPStorm right now

**Expected behavior**
no exception

**Versions**
OS: Linux Mint 20
PHPStorm: See in steps to reproduce
TYPO3 Plugin: 0.2.4

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:779)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:731)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:487)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:302)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:92)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:80)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:565)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:981)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:956)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1031)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:1024)
	at com.cedricziel.idea.typo3.container.IconProvider.collectIcons(IconProvider.java:76)
	at com.cedricziel.idea.typo3.container.IconProvider.collect(IconProvider.java:46)
	at com.cedricziel.idea.typo3.container.IconProvider.getInstance(IconProvider.java:30)
	at com.cedricziel.idea.typo3.TYPO3CMSProjectComponent.lambda$null$0(TYPO3CMSProjectComponent.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:819)
	at com.cedricziel.idea.typo3.TYPO3CMSProjectComponent.lambda$projectOpened$1(TYPO3CMSProjectComponent.java:37)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
// edit: added step 4

**Comment by cedricziel** [comment]
There is no version available yet for the 211 lineup of IntelliJ products; the plugin was downgraded to a way older version. In the meantime I have added an upper version constraint to the 0.2.4 version.

Please disable it for now and wait for an update.

Related: #348
