### ISSUE TITLE
Plugin exception on start: Read access is allowed from inside read-action (or EDT) only

### ISSUE THREAD

**Issue by sgrossberndt** [cedricziel/idea-php-typo3-plugin#403]
**Describe the bug**
Exception thrown on startup:

```
Details: Current thread: Thread[DefaultDispatcher-worker-10,5,main] 136458083
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 236953420

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:988)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.ensureUpToDate(FileBasedIndexScanUtil.java:48)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:237)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1146)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:225)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:62)
	at com.cedricziel.idea.typo3.startup.TYPO3CMSPostStartupActivity.containsPluginRelatedFiles(TYPO3CMSPostStartupActivity.java:71)
	at com.cedricziel.idea.typo3.startup.TYPO3CMSPostStartupActivity.checkProject(TYPO3CMSPostStartupActivity.java:59)
	at com.cedricziel.idea.typo3.startup.TYPO3CMSPostStartupActivity.runActivity(TYPO3CMSPostStartupActivity.java:26)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:279)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:278)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:278)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**To Reproduce**
1. Start PHPStorm 2022.3 with plugin TYPO3 CMS Support 223.9.0

**Expected behavior**

**Screenshots**

**Versions**
Please provide the version of your IDE and the plugin. To do so, you can paste the contents of "Help" ->  "About"
PhpStorm 2022.3
Build #PS-223.7571.212, built on December 1, 2022
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-56-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1972M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    org.toml.lang (223.7571.117)
    com.perl5 (2022.3)
    org.intellij.plugins.hcl (0.7.15)
    com.intellij.ideolog (203.0.30.0)
    String Manipulation (9.6.1)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    de.onigunn.intellij.xliff (0.2.0)
    org.sylfra.idea.plugins.linessorter (1.0.1)
    com.cedricziel.idea.typo3 (223.9.0)
    ru.adelf.idea.dotenv (2022.3)

Current Desktop: ubuntu:GNOME

**Comment by peterkraume** [comment]
I have the same error message. MacOS 12.6.1
